# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='second_friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_friend',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='login_apps.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
